### ISSUE TITLE
[Pixel][9,6]Fill the Pixel! 

### ISSUE THREAD

**Issue by aayushkatariaa** [OpenLake/PixOss#118]
- Your Name , ID , Batch
Aayush,12140010, DSAI 21
- What color do you wish to fill the Pixel with?
Green

**Comment by srs-sudeep** [comment]
[6,9] can't be coloured with saffron or green.
Did you mean [9,6]?

**Comment by tusharbansal22** [comment]
9,6 is assigned

**Comment by aayushkatariaa** [comment]
Merged by https://github.com/OpenLake/PixOss/pull/119
