### ISSUE TITLE
[Pixel][1,10]Fill the Pixel! 

### ISSUE THREAD

**Issue by ujjwi** [OpenLake/PixOss#129]
-Ujjwal Raj , 12241920, 2022
-Saffron

**Comment by ujjwi** [comment]
thik hai, to sudhar jaao, sun lo meri baat, thodi manners seekh lo, etiquette seekh lo, tameez seekhlo aur apna kaam dhandha dhoondho koi. Ye kya hai?

**Comment by immortalcodes** [comment]
Hi @ujjwi  what is the Purpose of this comment? Afaik doesn't have relevance to the repository

**Comment by ujjwi** [comment]
Sorry bhaiya,It wasn't anything specific, was a very random paragraph.On Aug 16, 2023 18:07, Madhur Jain ***@***.***> wrote: Warning! This message originated from outside the organization. Use caution on clicking links or opening attachments.

Hi @ujjwi  what is the Purpose of this comment? Afaik doesn't have relevance to the repository

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***<
 span>com>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OpenLake/PixOss/issues/129#issuecomment-1680527135",
"url": "https://github.com/OpenLake/PixOss/issues/129#issuecomment-1680527135",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by tusharbansal22** [comment]
Closing the Issue as not planned due to highly irrelevant comments
