### ISSUE TITLE
[Pixel][3,1]Fill the Pixel! 

### ISSUE THREAD

**Issue by rohitashwani1** [OpenLake/PixOss#38]
Rohit Ashwani, 12141390, 2025
Saffron

**Comment by tusharbansal22** [comment]
Ig [2,1] is already assigned. Please take some other pixel. @rohitashwani1

**Comment by rohitashwani1** [comment]
Can I take [3,1] then ?

**Comment by tusharbansal22** [comment]
yep, assigned, just change the header as well
